/*
 * This file is generated by jOOQ.
 */
package model


import model.tables.Task
import model.tables.records.TaskRecord

import org.jooq.TableField
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal


/**
 * A class modelling foreign key relationships and constraints of tables in
 * public.
 */
object Keys {

  // -------------------------------------------------------------------------
  // UNIQUE and PRIMARY KEY definitions
  // -------------------------------------------------------------------------

  val TASK_PKEY: UniqueKey[TaskRecord] = Internal.createUniqueKey(Task.TASK, DSL.name("task_pkey"), Array(Task.TASK.ID).asInstanceOf[Array[TableField[TaskRecord, _] ] ], true)
}
