/*
 * This file is generated by jOOQ.
 */
package model


import java.util.Arrays
import java.util.List

import model.tables.Task

import org.jooq.Catalog
import org.jooq.Table
import org.jooq.impl.SchemaImpl


object Public {

  /**
   * The reference instance of <code>public</code>
   */
  val PUBLIC = new Public
}

/**
 * This class is generated by jOOQ.
 */
class Public extends SchemaImpl("public", DefaultCatalog.DEFAULT_CATALOG) {

  /**
   * The table <code>public.task</code>.
   */
  def TASK = Task.TASK

  override def getCatalog: Catalog = DefaultCatalog.DEFAULT_CATALOG

  override def getTables: List[Table[_]] = Arrays.asList[Table[_]](
    Task.TASK
  )
}
