/*
 * This file is generated by jOOQ.
 */
package model


import model.tables.Task


/**
 * Convenience access to all tables in public.
 */
object Tables {

  /**
   * The table <code>public.task</code>.
   */
  def TASK = Task.TASK
}
